# -*- coding: utf-8 -*-
"""TPN°1_DL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cTIIcf3y02sYwBX_XUVT1BXSiJ1hOO7D

##Exercice1
"""

import numpy as np
import matplotlib.pyplot as plt
from tensorflow import keras
from sklearn.datasets import make_blobs

# Chargement des données et Normalisation
# Chargement des données MNIST
(X_train, y_train) , (X_test, y_test) = keras.datasets.mnist.load_data()
print('trainset:', X_train.shape)
print('testset:', X_test.shape)
# Normalisation des données
X_train = X_train.astype('float32') / 255
X_test = X_test.astype('float32')  / 255

# visualisation de quelques images
fig, ax = plt.subplots(nrows=1, ncols=10, figsize=(20, 4))
for i in range(10): ax[i].imshow(X_train[i], cmap='gray')
plt.tight_layout()
plt.show()

#configuration des couches de reseau des neurones
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(10, activation='softmax')
])
model.summary()

# Compilation du modele
model.compile(optimizer='adam',
loss=
keras.losses.SparseCategoricalCrossentropy(from_logits=True),
metrics=['accuracy'])
# Entrainement du modele
model.fit(X_train, y_train, epochs=10)

# Evaluation du modele
test_loss, test_acc = model.evaluate(X_test, y_test)
print('Test accuracy:', test_acc)

# modele prédictif (softmax)
prediction_model = keras.Sequential([model, keras.layers.Softmax()])
predict_proba = prediction_model.predict(X_test)
predictions = np.argmax(predict_proba, axis=1)
print(predictions[:10])
print(y_test[:10])

"""##Exercice N°2"""

# 1. Dataset
X, y = make_blobs( n_samples=100, n_features=2, centers=2, random_state=0)
y = y.reshape((y.shape[0], 1))
print('dimensions de X:', X.shape)
print('dimensions de y:', y.shape)
plt.scatter(X[:, 0], X[:, 1], c=y, cmap='summer')
plt.title("Dataset")
plt.show()

# 2. Fonctions du modèle

def initialisation(X):
    W = np.random.randn(X.shape[1], 1)
    b = np.random.randn(1)
    return W, b

def model(X, W, b):
    Z = X.dot(W) + b
    A = 1 / (1 + np.exp(-Z))  # sigmoid
    return A

def log_loss(A, y):
    epsilon = 1e-15  # éviter log(0)
    A = np.clip(A, epsilon, 1 - epsilon)
    return np.mean(-y * np.log(A) - (1 - y) * np.log(1 - A))

def gradients(A, X, y):
    dW = (1 / len(y)) * np.dot(X.T, A - y)
    db = (1 / len(y)) * np.sum(A - y)
    return dW, db

def update(dW, db, W, b, learning_rate):
    W = W - learning_rate * dW
    b = b - learning_rate * db
    return W, b

def predict(X, W, b):
    A = model(X, W, b)
    return A >= 0.5
from sklearn.metrics import accuracy_score

# 3. Entraînement

def artificial_neuron(X, y, learning_rate=0.1, n_iter=100):
    W, b = initialisation(X)
    Loss = []

    for i in range(n_iter):
        A = model(X, W, b)
        Loss.append(log_loss(A, y))
        dW, db = gradients(A, X, y)
        W, b = update(dW, db, W, b, learning_rate)
    y_pred = predict(X, W, b)
    print("Accuracy:", accuracy_score(y, y_pred))

    plt.plot(Loss)
    plt.title("Courbe de perte (Loss)")
    plt.xlabel("Itérations")
    plt.ylabel("Loss")
    plt.show()

    return W, b

# 4. Lancement

W, b = artificial_neuron(X, y)

# 5. Frontière de décision
fig, ax = plt.subplots(figsize=(9, 6))
ax.scatter(X[:, 0], X[:, 1], c=y, cmap='summer')

x1 = np.linspace(X[:,0].min() - 1, X[:,0].max() + 1, 100)
x2 = (-W[0] * x1 - b) / W[1]

ax.plot(x1, x2, c='red', lw=3)
ax.set_title("Frontière de décision")
plt.show()

"""###Exercice N°3"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow import keras

"""cette ligne permet de charger dataset"""

df = pd.read_csv('/content/AmesHousing.csv')

"""Ce code affiche un aperçu du dataset en montrant les 5 premières lignes afin de visualiser la structure des données et les colonnes."""

print("Aperçu des données:")
print(df.head())

""" Ce bloc crée un tableau récapitulatif pour chaque colonne contenant nombre des  valeurs manquante et leur pourcentage.

"""

#Valeurs manquantes
VM = pd.DataFrame({
'Colonne': df.columns.values,
'nbr de VM': df.isna().sum().values,
'% de VM': 100 * df.isna().sum().values / len(df),})
VM = VM[VM['nbr de VM'] > 0]
print(VM.sort_values(by='nbr de VM',
ascending=False).reset_index(drop=True))

#on affiche les variables catégorielles et les variables numériques
colonnes_avec_VM = df.columns[df.isna().sum() > 0]
for col in colonnes_avec_VM : print(col)
print(df[col].unique()[:5])
print('*'*30)

""" Remplacement des valeurs manquantes :
 Pour les colonnes numériques, on remplace par la moyenne de la colonne.
 Pour les colonnes catégorielles, on remplace par le mode (la valeur la plus fréquente ).
"""

#on remplace les VM numériques par la moyenne de la colonne
num_VM = ['Lot Frontage', 'BsmtFin SF 1', 'BsmtFin SF 2',
'Bsmt Unf SF', 'Total Bsmt SF', 'Bsmt Full Bath',
'Bsmt Half Bath', 'Garage Yr Blt', 'Garage Cars', 'Garage Area']
for n_col in num_VM:
    if n_col in df.columns:
        df[n_col] = df[n_col].fillna(df[n_col].mean())

#On remplace les VM nominales par le mode variable
nom_VM = [x for x in colonnes_avec_VM if x not in num_VM]
for nom_col in nom_VM:
  df[nom_col] =    df[nom_col].fillna(df[nom_col].mode().to_numpy()[0])

""" Après avoir identifié la nature des colonnes, on passe à l'encodage : on affiche d'abord les types de colonnes pour distinguer numériques et catégorielles"""

#encodage des variables catégorielles
#on affiche tout d'abord les types de données pour chaque colonne
types = pd.DataFrame({
'Colonne': df.select_dtypes(exclude='object').columns.values,
'Type': df.select_dtypes(exclude='object').dtypes.values})
print(types)

"""Encodage des variables catégorielles :'MS SubClass' est une variable nominale mais apparaît comme entière, on la convertit en chaîne
 On sélectionne les colonnes importantes pour l'analyse
 On utilise get_dummies pour transformer toutes les variables catégorielles en numériques
"""

#encodage des variables catégorielles,
#selon le descriptif de la dataset la colonne MS SubClass est nominale,
#Pandas a du mal à retourner son vrai type
df['MS SubClass'] = df['MS SubClass'].astype(str)
selection_de_variables = ['MS SubClass', 'MS Zoning', 'Lot Frontage',
'Lot Area',
             'Neighborhood', 'Overall Qual', 'Overall Cond',
             'Year Built', 'Total Bsmt SF', '1st Flr SF', '2nd Flr SF',
             'Gr Liv Area', 'Full Bath', 'Half Bath', 'Bedroom AbvGr',
             'Kitchen AbvGr', 'TotRms AbvGrd', 'Garage Area',
             'Pool Area', 'SalePrice']
df = df[selection_de_variables]
#la dataset comprendera maintenant que 67 variables
df = pd.get_dummies(df)

"""On sépare le dataset en données d'entraînement (80%) et de test (20%)
 On sépare également la variable cible 'SalePrice' du reste des données
"""

#fractionner dataset en des données de test et de train
train = df.sample(frac = 0.8, random_state = 9)
test = df.drop(train.index)
#variable cible
train_cible = train.pop('SalePrice')
test_cible = test.pop('SalePrice')

"""Pour que le modèle ne favorise pas certaines variables à cause de leurs valeurs, on standardise les données en centre les valeurs autour de 0 et les met à la même échelle."""

#Standardisation
variables_pred = train.columns
for col in variables_pred:
    col_moyenne = train[col].mean()
    col_ecart_type = train[col].std()
    if col_ecart_type == 0:
       col_ecart_type = 1e-20
    train[col] = (train[col] - col_moyenne) / col_ecart_type
    test[col] = (test[col] - col_moyenne) / col_ecart_type

"""Modèle de réseau de neurones avec plusieurs couches pour apprendre les relations, dropout pour éviter le sur-apprentissage, RMSprop comme optimiseur et MSE/MAE pour mesurer l'erreur."""

model1=keras.Sequential([
    layers.Dense(64,activation = 'relu', input_shape =
                 [train.shape[1]]),
    layers.Dropout(0.3, seed=2),
    layers.Dense(64, activation='swish'),
    layers.Dense(64, activation='relu'),
    layers.Dense(64, activation='swish'),
    layers.Dense(64, activation='relu'),
    layers.Dense(64, activation='swish'),
    layers.Dense(1)])

optimiseur=tf.keras.optimizers.RMSprop(learning_rate=0.001)
model1.compile(loss=tf.keras.losses.MeanSquaredError(),optimizer=optimiseur,metrics=['mae'])

"""Entrainement"""

training = model1.fit (train, train_cible, epochs = 70,
validation_split = 0.2)

"""Pour suivre l'entraînement de notre modèle, on crée l'historique afin de visualiser l'évolution de la MAE et de la MAE de validation à chaque époque.

"""

historique = pd.DataFrame(training.history)
historique['epoque'] = training.epoch
figure, axe = plt.subplots(figsize = (14,8))
num_epoque = historique.shape[0]
axe.plot(np.arange(0, num_epoque), historique["mae"],label = "Training MAE", lw = 3, color = 'red')
axe.plot(np.arange(0, num_epoque), historique["val_mae"],label =
"Validation MAE", lw = 3, color = 'blue')
axe.legend ()
plt.tight_layout()
plt.show()

test1 = test.iloc[[10]]
test_prediction = model1.predict(test1).squeeze()
test_label = test_cible.iloc[10]
print("Prédiction du modèle = {:.2f}".format(test_prediction))
print("Valeur actuelle = {:.2f}".format(test_label))

"""Note : On refait toutes les étapes précédentes : encodage, standardisation, séparation train/test
Ensuite, on crée et compile le modèle avec l’optimiseur Adam et la perte MSE
Entraînement du modèle avec suivi sur les données de validation
Évaluation sur le jeu de test et réalisation de quelques prédictions
Affichage de l’évolution de l’erreur MSE pendant l’entraînement
"""

# Importer les bibliothèques
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Charger la dataset
df = pd.read_csv("/content/AmesHousing.csv")

# Afficher les premières lignes
print(df.head())

#Valeurs manquantes
VM = pd.DataFrame({
'Colonne': df.columns.values,
'nbr de VM': df.isna().sum().values,
'% de VM': 100 * df.isna().sum().values / len(df),})
VM = VM[VM['nbr de VM'] > 0]
print(VM.sort_values(by='nbr de VM',
ascending=False).reset_index(drop=True))
#on affiche les variables catégorielles et les variables numériques
colonnes_avec_VM = df.columns[df.isna().sum() > 0]
for col in colonnes_avec_VM : print(col)
print(df[col].unique()[:5])
print('*'*30)
#on remplace les VM numériques par la moyenne de la colonne
num_VM = ['Lot Frontage', 'BsmtFin SF 1', 'BsmtFin SF 2',
'Bsmt Unf SF', 'Total Bsmt SF', 'Bsmt Full Bath',
'Bsmt Half Bath', 'Garage Yr Blt', 'Garage Cars', 'Garage Area']
for n_col in num_VM:
    if n_col in df.columns:
        df[n_col] = df[n_col].fillna(df[n_col].mean())
#On remplace les VM nominales par le mode variable
nom_VM = [x for x in colonnes_avec_VM if x not in num_VM]
for nom_col in nom_VM:
  df[nom_col] =    df[nom_col].fillna(df[nom_col].mode().to_numpy()[0])
#encodage des variables catégorielles
#on affiche tout d'abord les types de données pour chaque colonne
types = pd.DataFrame({
'Colonne': df.select_dtypes(exclude='object').columns.values,
'Type': df.select_dtypes(exclude='object').dtypes.values})
print(types)
#encodage des variables catégorielles,
#selon le descriptif de la dataset la colonne MS SubClass est nominale,
#Pandas a du mal à retourner son vrai type
df['MS SubClass'] = df['MS SubClass'].astype(str)
selection_de_variables = ['MS SubClass', 'MS Zoning', 'Lot Frontage',
'Lot Area',
             'Neighborhood', 'Overall Qual', 'Overall Cond',
             'Year Built', 'Total Bsmt SF', '1st Flr SF', '2nd Flr SF',
             'Gr Liv Area', 'Full Bath', 'Half Bath', 'Bedroom AbvGr',
             'Kitchen AbvGr', 'TotRms AbvGrd', 'Garage Area',
             'Pool Area', 'SalePrice']
df = df[selection_de_variables]
#la dataset comprendera maintenant que 67 variables
df = pd.get_dummies(df)
#fractionner dataset en des données de test et de train
train = df.sample(frac = 0.8, random_state = 9)
test = df.drop(train.index)
#variable cible
train_cible = train.pop('SalePrice')
test_cible = test.pop('SalePrice')
#Standardisation
variables_pred = train.columns
for col in variables_pred:
    col_moyenne = train[col].mean()
    col_ecart_type = train[col].std()
    if col_ecart_type == 0:
       col_ecart_type = 1e-20
    train[col] = (train[col] - col_moyenne) / col_ecart_type
    test[col] = (test[col] - col_moyenne) / col_ecart_type

# Création du modèle Deep Learning
model = keras.Sequential([
    layers.Dense(128, activation='relu', input_shape=[train.shape[1]]),
    layers.Dropout(0.2),
    layers.Dense(64, activation='relu'),
    layers.Dense(32, activation='relu'),
    layers.Dense(1)
])
model=keras.Sequential([
    layers.Dense(64,activation = 'relu', input_shape =
                 [train.shape[1]]),
    layers.Dropout(0.3, seed=2),
    layers.Dense(64, activation='swish'),
    layers.Dense(64, activation='relu'),
    layers.Dense(64, activation='swish'),
    layers.Dense(64, activation='relu'),
    layers.Dense(64, activation='swish'),
    layers.Dense(1)])

# Compilation avec Adam
optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
model.compile(optimizer=optimizer,loss='mean_squared_error',metrics=['mae'])

# Entrainement du modèle
Training = model.fit(train,train_cible,epochs=70,validation_split=0.2)
# Evaluation du modèle
loss, mae = model.evaluate(test, test_cible)
print("MAE sur test :", mae)
# Affichage du graphe MSE
historique = pd.DataFrame(Training.history)  # history renvoyé par model.fit()
historique['epoque'] = Training.epoch
figure, axe = plt.subplots(figsize=(14,8))
num_epoque = historique.shape[0]

# On trace la MSE sur les données d'entraînement et de validation
axe.plot(np.arange(0, num_epoque), historique["mae"], label="Training MAE", lw=3, color='red')
axe.plot(np.arange(0, num_epoque), historique["val_mae"], label="Validation MAE", lw=3, color='blue')

axe.legend()
plt.tight_layout()
plt.show()